homework/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include(('news.urls', 'news'), namespace='news')),


    path('ueditor/', include('DjangoUeditor.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('new_detail/<int:id>/',views.news_detail,name='detail'),
    path('new_list/',views.news_list,name='list')
]

news/models.py
from django.db import models
from DjangoUeditor.models import UEditorField
# Create your models here.


class BaseModel(models.Model):
    position = models.IntegerField(verbose_name='位置',default=0)
    is_show = models.BooleanField(verbose_name='是否显示',default=True)
    is_top = models.BooleanField(verbose_name='是否置顶',default=False)
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='跟新时间',auto_now = True)
    class Meta():
        abstract = True
#       导航
class Dbz_nav(BaseModel):
    name = models.CharField(verbose_name='导航名字',max_length=8)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '导航'
        verbose_name_plural = verbose_name


# 轮廓图
class Banner(BaseModel):
    image = models.ImageField(verbose_name='图片', upload_to='banner/%Y/%m/%d')
    url = models.URLField(verbose_name='跳转链接')
    name = models.CharField(verbose_name='图片描述',max_length=50)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '轮廓图'
        verbose_name_plural = verbose_name

# 公司介绍
class Company(BaseModel):
    name = models.CharField(verbose_name='公司名称',max_length=10)
    conpany_info = models.CharField(verbose_name='公司介绍',max_length=255)
    video = models.FileField(verbose_name='视屏',upload_to='video/%Y/%m/%d')
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '公司简介'
        verbose_name_plural = verbose_name

#  产品
class Product(BaseModel):
    cover = models.ImageField(verbose_name='产品样式',upload_to='product/%Y/%m/%d')
    name = models.CharField(verbose_name='产品名字',max_length=20)
    sub_title = models.CharField(verbose_name='副标题',max_length=30)
    def __str__(self):
        return  self.name
    class Meta():
        verbose_name = '产品'
        verbose_name_plural = verbose_name




# 产品分类
class Category(BaseModel):
    name = models.CharField(verbose_name='类名',max_length=10)
    product = models.ForeignKey(to=Product,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '分类'
        verbose_name_plural = verbose_name




# 合作伙伴
class Join_hands(BaseModel):
    company_info = models.CharField(verbose_name='公司简介',max_length=255)
    company_logo = models.ImageField(verbose_name='公司图片',upload_to='logo/%Y/%m/%d')
    def __str__(self):
        return self.company_info
    class Meta():
        verbose_name = '合作伙伴'
        verbose_name_plural = verbose_name

# 新闻分类
class NewsClassfly(BaseModel):
    name = models.CharField(verbose_name='新闻分类',max_length=10)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '新闻分类'
        verbose_name_plural = verbose_name

# 新闻
class News(BaseModel):
    cover = models.ImageField(verbose_name='封面',upload_to='news/%Y/%m/%d')
    news_info = models.CharField(verbose_name='文章简介',max_length=50)
    content = UEditorField(width=600, height=300, toolbars="full",
                           imagePath="news/%(basename)s_%(datetime)s.%(extname)s", filePath="files/")
    name = models.CharField(verbose_name='文章名字',max_length=25)
    browse = models.IntegerField(verbose_name='浏览量',default=0)
    classfly = models.ForeignKey(to=NewsClassfly,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '新闻'
        verbose_name_plural = verbose_name

# 员工表
class Staff(BaseModel):
    phont = models.ImageField(verbose_name="员工头像",upload_to="phont/%Y/%m/%d")
    job = models.CharField(verbose_name='职位',max_length=10)
    phone = models.CharField(verbose_name='手机号',max_length=11)
    email = models.CharField(verbose_name='邮箱',max_length=20)
    name = models.CharField(verbose_name='名字',max_length=20)
    address = models.CharField(verbose_name='地址',max_length=50)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '客户表'
        verbose_name_plural = verbose_name

class Second_menu(BaseModel):
    name = models.CharField(verbose_name='二级菜单名字',max_length=10)
    def __str__(self):
        return self.name
    class Meta():
        verbose_name = '二级菜单'
        verbose_name_plural = verbose_name

news/views.py
from django.shortcuts import render
from .models import Dbz_nav,NewsClassfly,News,Second_menu

from pure_pagination import PageNotAnInteger,Paginator
# Create your views here.
def news_detail(request,id):

    navs = Dbz_nav.objects.filter(is_show=True).all()
    news = News.objects.filter(is_show=True).filter(id=id).all()
    second_menus = Second_menu.objects.filter(is_show=True).all()
    # 增加阅读量
    now_new = News.objects.filter(id=id).first()
    if not news or not now_new :
        return render(request,'404.html')
    now_new.browse +=1
    now_new.save()

    #实现上一页下一页
    up_new = News.objects.filter(id=id-1).first()
    down_new = News.objects.filter(id=id+1).first()

    return render(request,'news_detail.html',locals())

def news_list(request):
    navs = Dbz_nav.objects.filter(is_show=True).all()
    news = News.objects.filter(is_show=True).all()
    classfly = NewsClassfly.objects.filter(is_show=True).all()
    second_menus = Second_menu.objects.filter(is_show=True).all()

    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1
    # arts = Article.objects.all()
    p = Paginator(news, per_page=1, request=request)
    articles = p.page(page)


    return render(request,'news_list.html',locals())

templates/_pagination.html
{% load i18n %}
<div class="pagination">
    {% if articles.has_previous %}
        <a href="?{{ articles.previous_page_number.querystring }}"
           class="prev">上一页</a>
    {% else %}
        <span class="disabled prev">上一页 </span>
    {% endif %}
    {% for page in articles.pages %}
        {% if page %}
            {% ifequal page articles.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if articles.has_next %}
        <a href="?{{ articles.next_page_number.querystring }}" class="next">下一页</a>
    {% else %}
        <span class="disabled next">下一页</span>
    {% endif %}
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta name="keywords" content=""/>
	<meta name="description" content=""/>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width,initial-scale=1, minimum-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="applicable-device" content="pc,mobile">
    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/iconfont.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/pagecss.css' %}"/>
</head>
{% block content %}
{% endblock %}
<!--页脚-->
<div class="FooterContainer">
	<div class="FooterZoneContainer">
		<div class="ModuleGridContainer clearfix" gridswidthmode="2">
			<div class="padding-1r0 hidden-sm hidden-xs col-md-3 col-lg-3">
				<div class="FooterImageGiant">
					<img src="{% static 'image/foot_logo.png' %}" alt="Logo图片">
				</div>
			</div>
			<div class="padding-1r0 hidden-sm hidden-xs col-md-3 col-lg-3">
				<div class="FooterImageTextGiant">
					<div class="FooterCenter">
						<div class="padding-10">
							<p><span>联系我们</span></p>
							<p><br></p>
							<p><span>联系电话：0310-123456789</span></p>
							<p><span>传真：0310-123456789</span></p>
							<p><span>电子邮箱：2996613775@qq.com</span></p>
							<p><span>地址：北京海淀区阿里巴巴</span></p>
						</div>
					</div>
				</div>
			</div>
			<div class="padding-1r0 hidden-sm hidden-xs col-md-3 col-lg-3">
				<div class="FooterCodeGiant">
					<img src="{% static 'image/code.png' %}" alt="微信">
				</div>
				<div class="codeTextContainer padding-10">
					<span>手机微信</span>
				</div>
			</div>
			<div class="padding-1r0 col-xs-12 col-sm-3 col-md-3 col-lg-3">
				<div class="FooterCodeCenter">
					<img src="{% static 'image/code.png' %}" alt="公众号">
				</div>
				<div class="codeTextContainer2 padding-10">
					<span>公众号</span>
				</div>
			</div>
		</div>
	</div>

	<div class="FooterCopyContainer">
		<div class="ModuleGridContainer clearfix" gridswidthmode="2">
			<div class="FooterCopyGiant">
				<div class="padding-10">
					<p><span>Copyright @ VillaGrandis All Rights Reserved  ICP备案号180006020号-3</span></p>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

templates/news_detail.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
{% block title %}
新闻详情
{% endblock %}


{% block content %}

    <!--网页头部-->
    {% load static %}
    <div class="container-fluid hidden-sm hidden-xs">
        <div class="ModuleGridContainer clearfix" gridswidthmode="2">
            <div class="col-lg-6 col-md-6">
                <img src="{%static 'image/logo.png'  %}" alt="Logo图片">
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="ModuleNavGiant clearfix">
                    {% for nav in navs %}
                        {% if nav.name == '产品展示' %}
                            <div class="main-nav-item-group productshow">

                        {% else %}
                            <div class="main-nav-item-group">

                       {% endif %}

                    {% if nav.name == '新闻资讯' %}
                    <a href="/" class="main-nav-item main-nav-item-hover">{{nav.name}}</a>
                    {% else %}
                        <a href="/" class="main-nav-item">{{nav.name}}</a>
                    {% endif %}
                    <div class="sub-nav-item-group">
                        <div class="arrow"></div>

                        <ul class="sub-nav-item-box">
                        {% for menu in second_menus %}
                            <li>
                                <a href="#" class="sub-nav-item">
                                    <span class="inner">
                                        {{menu.name}}
                                    </span>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>

                        </div>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

    <!--新闻详情-->
    {% for new in news %}
    <div class="ModuleGridContainer" gridswidthmode="2">
        <h2 class="newsDetailTitle">{{new.name}}</h2>
        <div class="newsSource">
            <span>关注：{{ new.browse }}</span>
            <span>发表时间：{{new.create_time}}</span>
        </div>
        <section>
            <article>
                <!--以下为富文本-->
                <p style="margin-top: 26px; padding: 0px; font-size: 16px; color: rgb(51, 51, 51); text-align: justify; font-family: arial; background-color: rgb(255, 255, 255); line-height: 2em;">
                    <span style="color: rgb(102, 102, 102);">
                        {{new.content | safe}}
                    </span>
                </p>
            </article>
        </section>

        <div class="PrevNext clearfix">
            <span class="prev">
                {% if up_new.id >= 1  %}
                    <a href="{% url 'news:detail' id=up_new.id %}">上一篇 : {{up_new}}</a>
                {% else %}
                    <span>上一篇 : ……</span>
                {% endif %}
            </span>
            <span class="next">
                {% if down_new.id >= 1  %}
                    <a href="{% url 'news:detail' id=down_new.id %}">下一篇 : {{down_new}}</a>
                {% else %}
                    <span>下一篇 : ……</span>
                {% endif %}
            </span>
        </div>
    </div>
    {% endfor %}

{% endblock %}

templates/news_list.html
{% extends 'base.html' %}
{% block title %}
    商品列表页
{% endblock %}
{% block content %}

{% load static %}

{#<!--网页头部-->#}
<div class="container-fluid hidden-sm hidden-xs">
        <div class="ModuleGridContainer clearfix" gridswidthmode="2">
            <div class="col-lg-6 col-md-6">
                <img src="{%static 'image/logo.png'  %}" alt="Logo图片">
            </div>

            <div class="col-lg-6 col-md-6">
                <div class="ModuleNavGiant clearfix">
                    {% for nav in navs %}
                        {% if nav.name == '产品展示' %}
                            <div class="main-nav-item-group productshow">

                        {% else %}
                            <div class="main-nav-item-group">

                       {% endif %}

                    {% if nav.name == '新闻资讯' %}
                    <a href="/" class="main-nav-item main-nav-item-hover">{{nav.name}}</a>
                    {% else %}
                        <a href="/" class="main-nav-item">{{nav.name}}</a>
                    {% endif %}
                    <div class="sub-nav-item-group">
                        <div class="arrow"></div>

                        <ul class="sub-nav-item-box">
                        {% for menu in second_menus %}
                            <li>
                                <a href="#" class="sub-nav-item">
                                    <span class="inner">
                                        {{menu.name}}
                                    </span>
                                </a>
                            </li>
                        {% endfor %}
                        </ul>

                        </div>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
{##}
{#<!--新闻列表大图-->#}
<div class="jumbotron imageGiant hidden-sm hidden-xs">
    <img src="{% static 'image/news_show.png' %}" alt="新闻列表大图">
</div>
<div class="jumbotron imageGiant hidden-lg hidden-md">
    <img src="{% static 'image/news_show_s.png' %}" alt="新闻列表大图">
</div>

<!--面包屑-->
<div class="ModuleGridContainer" gridswidthmode="2">
	<div class="ModuleBreadcrumbsGiant">
		<ol class="breadcrumb">
			<li><a href="" class="bcs-item">首页</a></li>
			<li><span class="separator">-</span></li>
			<li><a href="{% url 'news:list' %}" class="bcs-item">新闻资讯</a></li>
		</ol>
	</div>
</div>

{#<!--新闻主体-->#}
<div class="newsGridGiant">
	<div class="ModuleGridContainer clearfix" gridswidthmode="2">
		<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pad-mar0">
			<div class="newsCommonClsGiant">
				<header class="class-title">
					<span class="class-title-text">新闻动态</span>
					<span class="class-title-icon icon iconfont icon-jia hidden-lg hidden-md"></span>
				</header>
				<ul class="one-classify">
					<!--如果是当前类别的新闻，加激活样式即可： <li class="main-class-item active">-->
                    {% for classfly in classfly%}
					<li class="main-class-item">

						<a href="#">
							<p><i class="main-class-colorlump"></i></p>
							<span class="main-class-text">{{ classfly.name}}</span>
						</a>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>
		<div class="ModuleNewsListGiant col-xs-12 col-sm-12 col-md-9 col-lg-9 pad-mar0">
			<ul class="newsContainer clearfix">


                {% for new in articles.object_list %}
				<li class="news-item clearfix">
					<a href="{% url 'news:detail' id=new.id %}" class="clearfix">
						<div class="news-item-box">
							<div class="news-con-box">
								<div class="news-time">
									<time>{{ new.create_time | date:'m-d' }}</time>
									<div class="news-icon hidden-sm hidden-xs"><span></span></div>
								</div>
								<div class="newsCon">
									<p class="news-title">{{new.news_info}}</p>
								</div>
							</div>
							<div class="news-img">
								<img src="{{MEDIA_URL}}{{ new.cover }}" alt="让旧家电更懂你，迈联智能家居套件测评">
							</div>
						</div>
					</a>
				</li>
                {% endfor %}
                    {% include '_pagination.html' %}
			</ul>

        </div>
<!--手机加载更多-->
</div>
<script type="text/javascript" src="{% static 'js/dropload.min.js' %}"></script>
<script>
var viewWidth = window.screen.width;
if (viewWidth < 768) {
    $(function(){
        // 页数
        let page = 0;
        // 每页展示6个
        let size = 6;

        // dropload
        $('.newsGridGiant').dropload({
            scrollArea : window,
            loadDownFn : function(me){
                page++;
                // 拼接HTML
                let result = '';
                $.ajax({
                    type: 'GET',
                    url: 'http://xxx?page='+page+'&size='+size,
                    dataType: 'json',
                    success: function(data){
                        let arrLen = data.length;
                        if(arrLen > 0){
                            for(let i=0; i<arrLen; i++){
                                result +=   '<li class="news-item clearfix">' +
												'<a href="news_detail.html" class="clearfix">' +
													'<div class="news-item-box">' +
														'<div class="news-con-box">' +
															'<div class="news-time">' +
																'<time>09-07</time>' +
																'<div class="news-icon hidden-sm hidden-xs"><span></span></div>' +
															'</div>' +
															'<div class="newsCon">' +
																'<p class="news-title">旧家电更懂你，迈联智能家居套件测评</p>' +
															'</div>' +
														'</div>' +
														'<div class="news-img">' +
															'<img src="image/news1.jpg" alt="让旧家电更懂你，迈联智能家居套件测评">' +
														'</div>' +
													'</div>' +
												'</a>' +
											'</li>';
                            }
                        // 如果没有数据
                        }else{
                            // 锁定
                            me.lock();
                            // 无数据
                            me.noData();
                        }
                        // 为了测试，延迟1秒加载
                        // setTimeout(function(){
                            // 插入数据到页面，放到最后面
                            $('.ModuleNewsListGiant ul').append(result);
                            // 每次数据插入，必须重置
                            me.resetload();
                        // },1000);
                    },
                    error: function(xhr, type){
                        // alert('Ajax error!');
                        // 即使加载出错，也得重置
                        me.resetload();
                    }
                });
            }
        });
    });
}
</script>

{% endblock %}